<?php

return [ 
  
   
    
    'Rapido'=>'Rapido',
    'All Kinds'=>'All Kinds',
    'Sum of Dragon/Tiger/Tie'=>'',
    'FixedPlace'=>'FixedPlace',
    'B/S 1st'=>'B/S 1st',
    'P/C 1st'=>'P/C 1st',
    'Big'=>'Big',
    'Prime'=>'Prime',
    'Composite'=>'Composite',
    'Small'=>'Small',
    'O/E 1st'=>'O/E 1st',
    'Odd'=>'Odd',
    'O/E 1st'=>'O/E 1st',
    'Even'=>'Even',
    'B/S sum'=>'B/S sum',
    'D/T sum'=>'D/T sum',
    'Dragon'=>'Dragon',
    'Tiger'=>'Tiger',
    'T sum'=>'T sum',

    'Odd'=>'Odd',
    'Tie'=>'Tie',
    'O/E sum'=>'O/E sum',
    'P/C 2nd'=>'P/C 2nd',
    'P/C 3rd'=>'P/C 3rd',
    'Prime'=>'Prime',
    'O/E 3rd'=>'O/E 3rd',
    'B/S 3rd'=>'B/S 3rd',
    'B/S 2nd'=>'B/S 2nd',
    'Royal 5'=>'Royal 5',
    '2 sides'=>'2 sides',
    'Fixed Place'=>'Fixed Place',
    'Sum of Top Two'=>'Sum of Top Two',
    'D/T 1st'=>'D/T 1st',
    'Tiger'=>'Tiger',
    
    'Dragon'=>'Dragon',
    'O/E 2nd'=>'O/E 2nd',
    'O/E 3rd'=>'O/E 3rd',
    'O/E 4th'=>'O/E 4th',
    'D/T 5th'=>'D/T 5th',
    'D/T 4th'=>'D/T 4th',
    'B/S 6th'=>'B/S 6th',
    'B/S 7th'=>'B/S 7th',
    'B/S 8th'=>'B/S 8th',
    'B/S 9th'=>'B/S 9th',
    'B/S 10th'=>'B/S 10th',
    'O/E 6th'=>'O/E 6th',
    'O/E 7th'=>'O/E 7th',
    'O/E 8th'=>'O/E 8th',
    'O/E 9th'=>'O/E 9th',
    'O/E 10th'=>'O/E 10th',
    'GuessNumer'=>'GuessNumer',
    'B/S GuessNumber'=>'B/S GuessNumber',
    'Specific Any Triple'=>'Specific Any Triple',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',
    ''=>'',



];
