const a = {
    "Game Instructions: Select one number each from the 1st, 2nd, 3rd, 4th, and 5th places to form one bet. If the selected numbers match the drawn numbers exactly and in the correct order, you win.": "玩法说明：从万位、千位、百位、十位、个位上各选1个号码组成1注。所选号码与开奖号码相同，且顺序一致，即中奖。中奖范例：投注方案：1,2,3,4,5；开奖号码：1,2,3,4,5，即中奖。",
    "Game Instructions: Choose one number from the 1st, 2nd, 3rd, and 4th places to form one bet. If the selected numbers match the winning numbers 1st, 2nd, 3rd, and 4th places respectively, and in the same order, it counts as a win. Winning Example: Betting scheme: 1,2,3,4; Winning numbers: 1,2,3,4,* (where * represents any number for the units place). This results in a win.":"玩法说明：从万位、千位、百位、十位上各选择1个号码组成1注。所选号码与开奖号码的万位、千位、百位、十位相同，且顺序一致，即中奖。中奖范例：投注方案：1,2,3,4；开奖号码：1,2,3,4,*，即中奖。",
    "Game Instructions: Select one number each from the 1st, 2nd, and 3rd places to form a bet. If the chosen numbers match the winning numbers in the 1st, 2nd, and 3rd places, and in the exact order, then you win. For Examplea: Betting plan: 3, 4, 5; Winning numbers: 3, 4, 5, *, *. In this case, you win.":"玩法说明：从万位、千位、百位中各选择1个号码组成1注，所选号码与开奖号码的万位、千位、百位相同，且顺序一致，即为中奖。中奖范例：投注方案：3,4,5；开奖号码：3,4,5,*,*，即中奖。",
    "Game Instructions: Select one number each from the 2nd, 3rd and 4th places to form a bet. If the chosen numbers match the winning numbers in the 2nd, 3rd and 4th places, and in the exact order, then you win. For Examplea: Betting plan: 3, 4, 5; Winning numbers: *, 3, 4, 5, *. In this case, you win.":"玩法说明：从千位、百位、十位中各选择1个号码组成1注，所选号码与开奖号码的千位、百位、十位相同，且顺序一致，即为中奖。中奖范例：投注方案：3,4,5；开奖号码：*,3,4,5,*，即中奖。",
    "Game Instructions: Select one number each from the 2nd, 3rd and 4th places to form a bet. If the chosen numbers match the winning numbers in the 2nd, 3rd and 4th places, and in the exact order, then you win. For Examplea: Betting plan: 3, 4, 5; Winning numbers: *, *, 3,4, 5,. In this case, you win.":"玩法说明：从百位、十位、个位中各选择1个号码组成1注，所选号码与开奖号码的百位、十位、个位相同，且顺序一致，即为中奖。中奖范例：投注方案：3,4,5；开奖号码：*,*,3,4,5，即中奖。",
    "Game Instructions: Select one number each from the 1st and 2nd places to form one bet. If the chosen numbers match the 1st and 2nd places of the winning number, and in the same order, you win. Winning Example: Betting Scheme: 1,2; Winning Number: 1,2,*,*,*; this results in a win.":"玩法说明：从万位、千位上各选择1个号码组成1注。所选号码与开奖号码的万位、千位相同，且顺序一致，即中奖。中奖范例：投注方案：1,2；开奖号码：1,2,*,*,*，即中奖。",
    "Game Instructions: Select one number each from the 4th and 5th places to form one bet. If the chosen numbers match the 4th and 5th places of the winning number, and in the same order, you win. Winning Example: Betting Scheme: 1,2; Winning Number: *,*,*,1,2; this results in a win.":"玩法说明：从十位、个位上各选择1个号码组成1注。所选号码与开奖号码的十位、个位相同，且顺序一致，即中奖。中奖范例：投注方案：1,2；开奖号码：*,*,*,1,2，即中奖。",
    "Game Instructions: Choose one number for any position from 1st , 2nd , 3rd , 4th or 5th to make one bet. If the selected number matches the number in the corresponding position of the winning number, you win. Winning Example: Betting Scheme: 3,-,-,-,-; Winning Number: 3,*,*,*,; this results in a win.":"玩法说明：从万位、千位、百位、十位、个位任意位置选择1个号码组成1注，所选号码与相同位置上的开奖号码一致，即中奖。中奖范例：投注方案：3,-,-,-,-；开奖号码：3,*,*,*,* ，即中奖。",
    "Game Instructions: Choose two numbers to make one bet. If the selected numbers appears in the 1st , 2nd or 3rd place of the winning number, you win. Winning Example: Betting Scheme: 3; Winning Number: 1,3,2,*,*,; this results in a win.":"玩法说明：选择1个号码组成1注。开奖号码的万位、千位、百位中包含所选号码，即中奖。中奖范例：投注方案：3；开奖号码：1,3,2,*,*，即中奖。",
    "Game Instructions: Choose atleast one selection from the 1st and 2nd places to form a bet. Ranges include: Big: 5-9 Small: 0-4 Odd: 1,3,5,7,9 Even: 0,2,4,6,8 Make one bet with these choices. If the selected forms for the respective positions match the forms and positions of the winning number, you win. Winning Example: Betting Scheme: 1st: Big, 2nd: Small; Winning Number: 9,4,,,*; this results in a win.":"玩法说明：分别选择万位和千位的1个形态（大：5-9；小：0-4；单：1,3,5,7,9； 双：0,2,4,6,8)，组成1注。所选位置的形态与开奖号码的位置与形态相同，即中奖。中奖范例：投注方案：万位：大，千位：小；开奖号码：9,4,*,*,*，即中奖。",
    "Game Instructions: Choose one number to place a bet on. If the selected number appears in the 1st, 2nd, 3rd, 4th or 5th place of the winning number, you win. Winning Example: Betting Scheme: 1; Winning Number: 9,8,1,2,8; this results in a win.":"玩法说明：选择1个号码组成1注。开奖号码的万位、千位、百位、十位、个位中包含所选号码，即中奖。中奖范例：投注方案：1；开奖号码：9,8,1,2,8，即中奖。",
    "Game Instructions: Choose any two positions from the 1st, 2nd, 3rd, 4th, and 5th. Select one number for each of the two chosen positions to form one bet. If the winning numbers match the numbers in the selected two positions in the exact order, then you win. Winning Example: Betting scheme: 1,2,-,-,-; Winning numbers: 1,2,*,*,* &mdash; you win.":"玩法说明：从万位、千位、百位、十位、个位中任意选择2个位置，在这2个位置上各选择1个号码组成1注。开奖号码与所选2个位置的号码相同，且顺序一致，即中奖。中奖范例：投注方案：1,2,-,-,-；开奖号码：1,2,*,*,*，即中奖。",
    "1Game Instructions: Select any three positions from the 1st, 2nd, 3rd, 4th and 5th. Choose one number for each of these three positions to form one bet. If the winning numbers match the numbers in the selected three positions in the exact order, then you win. Winning Example: Betting scheme: 1,2,3,-,-; Winning numbers: 1,2,3,*,*, &mdash; you win.":"玩法说明：从万位、千位、百位、十位、个位中任意选择3个位置，在这3个位置上各选择1个号码组成1注。开奖号码与所选3个位置的号码相同，且顺序一致，即中奖。中奖范例：投注方案：1,2,3,-,-；开奖号码：1,2,3,*,*，即中奖。",
    "Game Instructions: Choose one number from each of any four positions among the 1st, 2nd, 3rd, 4th and 4th to form one bet. If the winning numbers match the chosen numbers in the selected four positions and in the same order, then you win. Winning Example: Betting scheme: 1,2,3,-,4; Winning numbers: 1,2,3,*,4 &mdash; you win.":"玩法说明：从万位、千位、百位、十位、个位中任意选择四个位置，在这四个位置上各选择1个号码组成1注。开奖号码与所选四个位置的号码相同，且顺序一致，即中奖。中奖范例：投注方案：1,2,3,-,4；开奖号码：1,2,3,*,4，即中奖。",
    "Game Instructions: Choose one form from a group of positions to form one bet. Compare the size of the winning numbers in this group of positions. If the former is greater than the latter, it's 'Dragon'; if the former is less than the latter, it's 'Tiger'; if the numbers are the same, it's 'Tie'. If the selected form matches the winning form, then you win. Winning Example: Betting scheme: 1st, 2nd: Tie; Winning numbers: 0,0,*,*,* &mdash; you win.":"玩法说明：从1组位置中选择1个形态组成1注，1组位置中的开奖号码比较大小，前者大于后者为龙，反之为虎，号码相同则为和。所选形态与开奖形态一致，即中奖。中奖范例：投注方案：万千和；开奖号码：0,0,*,*,*，即中奖。",
    "Game Instructions: Choose one form as one bet. If the selected form matches the winning form, regardless of the order, you win. Four of a Kind: One number appears once, and another number appears four times in the winning numbers. Gourd: One number appears twice, and another number appears three times in the winning numbers. Straight: The winning numbers form a sequence of five consecutive numbers. 9 is connected to 0, and 0 is connected to 1. Three of a Kind: One number appears three times, and the other two numbers are different in the winning numbers. Two Pairs: Two pairs of double numbers appear in the winning numbers. One Pair: One pair of double numbers appears, and the other three numbers are different in the winning numbers. High Card: The five numbers in the winning numbers are all different and not in sequence. Winning Example: Betting scheme: Straight; Winning numbers: 0,9,1,3,2 &mdash; you win.":"玩法说明：选择1个形态为1注，所选形态和开奖形态相同，顺序不限，即中奖。 四条：开奖号码中1个号码出现1次，另1个号码出现4次； 葫芦：开奖号码中1个号码出现2次，另1个号码出现3次； 顺子：开奖号码为5个顺序相连的号码；9与0相连，0与1相连； 三条：开奖号码中1个数字出现3次，其余2个号码不相同； 两对：开奖号码中出现两对二重号； 一对：开奖号码中出现二重号，而另外3个号码不相同； 单牌：开奖号码的5个数字各不相同且不为顺子。中奖范例：投注方案：顺子；开奖号码：0,9,1,3,2，即中奖。",
    "Game Instructions: Choose one form as one bet. If the selected form matches the form of the three numbers corresponding to the winning numbers, regardless of the order, you win. TOAK: Three numbers are the same; Straight: Three consecutive numbers; 9 is connected to 0, and 0 is connected to 1; Pair: One of the three numbers appears twice, and the other number appears once (e.g., 151, 887); Half-Streak: Three numbers are all different, and only two of them are consecutive (e.g., 238, 769); Mixed: Three numbers are all different and not consecutive with each other (e.g., 357, 962). Winning Example: Betting scheme: Front Three: Leopard; Winning numbers: 0,0,0,*,* &mdash; you win.":"玩法说明：选择1个形态为1注，所选形态和开奖号码对应位置的3个数字的形态相同，顺序不限，即中奖。 豹子：3个号码相同； 顺子：3个顺序相连的号码；9与0相连，0与1相连； 对子：3个数字中有1个数字出现2次，另1个数字出现1次（如：151、887）； 半顺：3个数字各不相同，且其中只有2个数字相连（如：238、769）； 杂六：3个数字各不相同且互不相连（如：357、962）。中奖范例：投注方案：前三：豹子；开奖号码：0,0,0,*,*，即中奖。",
    "Game Instructions: Choose one form as one bet. If the selected form matches the form of the winning numbers, you win. 1. No Bull: The sum of any three digits in the winning numbers cannot be a multiple of 0 or 10. 2. Bull Bull: The sum of any three digits in the winning numbers can be a multiple of 0 or 10, and the units digit of the sum of the other two numbers is 0. 3. Bull 1 to Bull 9: The sum of any three digits in the winning numbers can be a multiple of 0 or 10, and the units digit of the sum of the other two numbers matches the selected number. 4. Big Bull: Bull Bull, Bull 9, Bull 8, Bull 7, Bull 6. 5. Small Bull: Bull 5, Bull 4, Bull 3, Bull 2, Bull 1. 6. Odd Bull: Bull 1, Bull 3, Bull 5, Bull 7, Bull 9. 7. Even Bull: Bull 2, Bull 4, Bull 6, Bull 8, Bull Bull. Winning Example: Betting scheme: Bull 1; Winning numbers: 9,0,1,1,0 &mdash; you win.":"玩法说明：选择1个形态为1注，所选形态与开奖形态相同，即中奖。 1、无牛：开奖号码中任意3位数相加都无法是0或10的倍数； 2、牛牛：开奖号码中任意3位数相加可以为0或10的倍数，另外2个数字相加的个位数为0； 3、牛1-牛9：开奖号码中任意3位数相加可以为0或10的倍数，另外2个数字相加的个位数为所选号码； 4、牛大：牛牛，牛9、牛8、牛7、牛6； 5、牛小：牛5、牛4、牛3、牛2、牛1； 6、牛单：牛1、牛3、牛5、牛7、牛9； 7、牛双：牛2、牛4、牛6、牛8、牛牛中奖范例：投注方案：牛1；开奖号码：9,0,1,1,0，即中奖。",
  
  
  
    // "_comment": "from all 5 straight manual. to all 5 group ",
    "Game Instructions: Enter one five-digit number to form a single bet. If the entered number matches the drawn number exactly and in the correct order, you win. Winning Example: Betting scheme: 12345; Winning numbers: 1,2,3,4,5. This results in a win":"玩法说明：录入1个5位数的号码组成1注。录入的号码与开奖号码相同，且顺序一致，即中奖。中奖范例：投注方案：12345；开奖号码：1,2,3,4,5，即中奖。",
    // "_comment": "all 5 straight combo.",
    "Game Instructions: Select one number from the 1st, 2nd, 3rd, 4th, and 5th places to form combinations of 1 to 5, totaling 5 bets. If the selected number for the 5th place matches the winning number's 5th place, you win the 5th position prize. If the selected numbers for the 4th and 5th places match the winning numbers for the 4th and 5th places, you win the 4th and 5th position prizes and so on. Therefore, you can win up to 5 prizes at the same time. Winning Example: Betting scheme: 1,2,3,4,5; Winning numbers: 1,2,3,4,5. This results in wins for -,-,-,-,5; -,-,-,4,5; -,-,3,4,5; -,2,3,4,5; and 1,2,3,4,5, one bet each.":"玩法说明：从万位、千位、百位、十位、个位上各选1个号码组成1~5星的组合，共5注。所选号码的个位与开奖号码的个位相同，则中个位定位胆；所选号码的十位、个位与开奖号码的十位、个位相同，则中个位定位胆及后二直选。依此类推，最多可同时中5个奖。中奖范例：投注方案：1,2,3,4,5；开奖号码：1,2,3,4,5，即中-,-,-,-,5、-,-,-,4,5、-,-,3,4,5、-,2,3,4,5、1,2,3,4,5,各一注。",
  "Game Instructions: Choose 5 numbers to form one bet. If the selected numbers match the winning numbers (order doesn't matter), it counts as a win. Winning Example: Betting scheme: 0,2,3,8,9; Winning numbers: 9,8,0,2,3. This results in a win.":"玩法说明：选择5个号码组成1注，所选号码与开奖号码相同(顺序不限)，即为中奖。中奖范例：投注方案：0,2,3,8,9；开奖号码：9,8,0,2,3，即中奖。",
  "Game Instructions: Select 1 pair (double number) and 3 single numbers to form one bet. If the winning numbers contain the selected 3 single numbers, and the selected pair appears twice in the winning numbers, it counts as a win. Winning Example: Betting scheme: Double number: 1, Single numbers: 2,3,4; Winning numbers: 1,2,3,4,1. This results in a win.":"玩法说明：选择1个二重号和3个单号组成1注。开奖号码包含所选3个单号，且所选二重号在开奖号码中出现了2次，即中奖。中奖范例：投注方案：二重号：1，单号：2,3,4；开奖号码：1,2,3,4,1，即中奖。",
  "Game Instructions: Choose 2 pairs (double numbers) and 1 single number to form one bet. If the winning numbers contain the selected single number, and each of the selected 2 pairs appears twice in the winning numbers, it counts as a win. Winning Example: Betting scheme: Double numbers: 2,8, Single number: 0; Winning numbers: 2,8,0,8,2. This results in a win.":"玩法说明：选择2个二重号和1个单号组成1注。开奖号码包含所选单号，且所选2个二重号在开奖号码中各出现2次，即中奖。中奖范例：投注方案：二重号：2,8，单号：0；开奖号码：2,8,0,8,2，即中奖。",
  "Game Instructions: Choose 1 triplet (triple number) and 2 single numbers to form one bet. If the winning numbers contain the selected 2 single numbers, and the selected triplet appears three times in the winning numbers, it counts as a win. Winning Example: Betting scheme: Triplet: 8, Single numbers: 0,2; Winning numbers: 0,8,2,8,8. This results in a win.":"玩法说明：选择1个三重号和2个单号组成1注。开奖号码包含所选2个单号，且所选三重号在开奖号码中出现3次，即中奖。中奖范例：投注方案：三重号：8，单号：0,2；开奖号码：0,8,2,8,8，即中奖。",
  "Game Instructions: Choose 1 triplet (triple number) and 1 pair (double number) to form one bet. If the selected triplet appears three times and the selected pair appears twice in the winning numbers, it counts as a win. Winning Example: Betting scheme: Triplet: 8, Pair: 2; Winning numbers: 2,2,8,8,8. This results in a win.":"玩法说明：选择1个三重号和1个二重号组成1注。开奖号码中所选三重号出现3次，且所选二重号出现2次，即中奖。中奖范例：投注方案：三重号：8，二重号：2；开奖号码：2,2,8,8,8，即中奖。",
  "Game Instructions: Choose 1 quadruplet (fourfold number) and 1 single number to form one bet. If the winning numbers contain the selected single number, and the selected quadruplet appears four times in the winning numbers, it counts as a win. Winning Example: Betting scheme: Quadruplet: 8, Single number: 2; Winning numbers: 8,8,2,8,8. This results in a win.":"玩法说明：选择1个四重号和1个单号组成1注。开奖号码包含所选单号，且所选四重号在开奖号码中出现4次，即中奖。中奖范例：投注方案：四重号：8，单号：2；开奖号码：8,8,2,8,8，即中奖。"
  
}